Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,8 +30,9 @@ jobs:
       - name: Install dependencies
         run: flutter pub get
 
-      - name: Test Dart Compilation
-        run: flutter build bundle
+      - name: Check Specific Errors
+        run: |
+          flutter analyze --no-fatal-warnings | grep -E "error •" || true
 
       - name: Build Debug APK
         run: flutter build apk --debug
